/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/animation1.glb 
*/
"use client";

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Animation1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/animation1.glb");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    names.map((name) => {
      setTimeout(() => {
        actions[name].reset().fadeIn(0.5).play();
      }, 1);
      return actions[name].reset().fadeOut(0.5);
    });
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="backflip" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="mesh18">
            <skinnedMesh
              castShadow
              name="mesh18_1"
              geometry={nodes.mesh18_1.geometry}
              material={materials["nr2_tex01.png"]}
              skeleton={nodes.mesh18_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="mesh18_2"
              geometry={nodes.mesh18_2.geometry}
              material={materials["nr2_tex02.png"]}
              skeleton={nodes.mesh18_2.skeleton}
            />
            <skinnedMesh
              castShadow
              name="mesh18_3"
              geometry={nodes.mesh18_3.geometry}
              material={materials["nr2_eye.png"]}
              skeleton={nodes.mesh18_3.skeleton}
            />
          </group>
        </group>
        <group
          name="kick"
          position={[0, -1, 0]}
          rotation={[Math.PI / 2, 0, -3.036]}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips_2} />
        </group>
        {/* <group name="stand-to-sit" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_3} />
        </group> */}
        {/* <group name="sitting" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_4} />
        </group> */}
        <group name="kicking" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
        </group>
        <group name="flipkick" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_5} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/animation1.glb");
