import type { Metadata } from "next";
import { Urbanist, Bebas_Neue } from "next/font/google";
import "./globals.css";
const inter = Urbanist({ subsets: ["latin"] });
const bebas = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-slate-700 text-slate-100">
      <body className={bebas.className}>{children}</body>
    </html>
  );
}
